stages:
  split_data:
    cmd: python src/1_data_splitting.py
    deps:
    - data/raw/raw.csv
    - src/1_data_splitting.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - models/data/scaler.pkl
  normalize_data:
    cmd: python src/2_data_normalizing.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - models/data/scaler.pkl
    - src/2_data_normalizing.py
    outs:
    - data/processed/X_test_scaled.csv
    - data/processed/X_train_scaled.csv
  grid_search:
    cmd: python src/3_gridsearch.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - src/3_gridsearch.py
    outs:
    - models/data/best_params.pkl
  train_model:
    cmd: python src/4_model_training.py
    deps:
    - data/processed/X_train_scaled.csv
    - data/processed/y_train.csv
    - models/data/best_params.pkl
    - src/4_model_training.py
    outs:
    - models/models/trained_model.pkl
  evaluate_model:
    cmd: python src/5_model_evaluating.py
    deps:
    - data/processed/X_test_scaled.csv
    - data/processed/y_test.csv
    - models/models/trained_model.pkl
    - src/5_model_evaluating.py
    outs:
    - metrics/scores.json
    - models/data/prediction.csv
